# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened
      - edited
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v1
      - name: commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit --allow-empty -m "${{ github.event.pull_request.title }}" -m "" -m "4621fd21-37a6-4dd0-b3f5-a71c28bc2b01"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
